/**
 * Agent Outbound Logs
 *
 * Logs HTTP requests generated by the agent.
 * Automatically intercepted by HTTPInterceptor - no manual logging needed.
 */

import pool from '@/lib/db'

async function withClient<T>(callback: (client: any) => Promise<T>): Promise<T> {
  if (!pool) {
    throw new Error('Database not available')
  }

  const client = await pool.connect()
  try {
    return await callback(client)
  } finally {
    client.release()
  }
}

export type OutboundLogRequestType = 'tool_use' | 'memory_search' | 'memory_add'

export interface OutboundLogEntry {
  userId: string
  conversationId: string
  requestType: OutboundLogRequestType
  endpoint: string
  method: string
  requestPayload?: any
  responsePayload?: any
  status: 'success' | 'error'
  errorMessage?: string
  durationMs?: number
}

/**
 * Log an outbound HTTP request
 * Called automatically by HTTPInterceptor
 */
export async function logOutboundRequest(entry: OutboundLogEntry): Promise<void> {
  try {
    await withClient(async (client) => {
      const query = `
        INSERT INTO agent_outbound_logs (
          user_id, conversation_id, request_type, endpoint, method,
          request_payload, response_payload, status, error_message, duration_ms
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
      `

      await client.query(query, [
        entry.userId,
        entry.conversationId,
        entry.requestType,
        entry.endpoint,
        entry.method,
        entry.requestPayload ? JSON.stringify(entry.requestPayload) : null,
        entry.responsePayload ? JSON.stringify(entry.responsePayload) : null,
        entry.status,
        entry.errorMessage || null,
        entry.durationMs || null,
      ])
    })
  } catch (error) {
    // Don't throw - logging failures shouldn't break the flow
    console.error('[OutboundLog] Failed to log request:', error)
  }
}
